<a href="https://colab.research.google.com/github/DasariRishikesh/Python_with_MachineLearning/blob/main/Python_with_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pyhton with Machine Learning

##Numpy

#### Introduction to numpy

In [ ]:
import numpy as np
a = np.array([1,2,3,4])

*  Intialize array

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a2 = np.array([[1,2,3,4,5],[10,20,30,40]])

<ipython-input-18-ac16d04e47d0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1,2,3,4,5],[10,20,30,40]])


In [ ]:
a2

array([list([1, 2, 3, 4, 5]), list([10, 20, 30, 40])], dtype=object)

In [ ]:
type(a2) # type of the array

numpy.ndarray

*  Making Zeroes of all elements

In [ ]:
a1 = np.zeros((1,5))

In [ ]:
a1

array([[0., 0., 0., 0., 0.]])

In [ ]:
a2 = np.zeros((5,5))
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

*  Making The All elements same



full((size of the array along with the dimension), Value)

In [113]:
k = np.full((3,3,3),1)

In [114]:
k

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

*  Declare range of the arrray

(initial value, Final Value, Increment)

In [ ]:
l = np.arange(90,99,8)

In [ ]:
l

array([90, 98])

*  Passing random values

random.randint(start value,endvalue, Number of elements)

In [ ]:
 import numpy as np

In [ ]:
r = np.random.randint(3,7,4)
r

array([3, 6, 3, 6])

*  Random float points using rand

random.rand(number of rows or dimentions, number of rows in single dimension,Number of cloumns)

In [ ]:
ir = np.random.rand(2,5,4)
ir

array([[[0.85273206, 0.28958883, 0.87866551, 0.94574652],
        [0.12181155, 0.59262505, 0.20712191, 0.5142399 ],
        [0.06381569, 0.72896195, 0.1888137 , 0.72344889],
        [0.24185891, 0.3577034 , 0.37453504, 0.23581322],
        [0.66992718, 0.38863676, 0.25526386, 0.773159  ]],

       [[0.31008368, 0.20027366, 0.43278066, 0.74444885],
        [0.89748475, 0.66243957, 0.75853795, 0.97836724],
        [0.5296578 , 0.49393908, 0.48572778, 0.83055239],
        [0.27158704, 0.6976168 , 0.73196061, 0.10320711],
        [0.27813358, 0.56517061, 0.04490238, 0.32414503]]])

*  Shape and Reshape

In [ ]:
w = np.array([[[0.46632969, 0.3848112 , 0.83590619, 0.44005272], [0.9816671 , 0.10282616, 0.11472637, 0.28133451]], [[0.50586517, 0.2071658 , 0.99934125, 0.06517334], [0.93871074, 0.00633421, 0.5426788 , 0.85028254]]])
w.shape

(2, 2, 4)

In [ ]:
w.shape = (2,4,2)

In [ ]:
w

array([[[0.46632969, 0.3848112 ],
        [0.83590619, 0.44005272],
        [0.9816671 , 0.10282616],
        [0.11472637, 0.28133451]],

       [[0.50586517, 0.2071658 ],
        [0.99934125, 0.06517334],
        [0.93871074, 0.00633421],
        [0.5426788 , 0.85028254]]])

In [120]:
z = np.array([[1,2,3,4],[5,6,7,8]])
z.shape = (4,2)
z


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Working with stack menthods in numpy, We have
*  vstack()
*  hstack()
*  column_stack()

V stack():
Merge n arrays in 2 dimension

In [131]:
import numpy as np
e = np.array([1,2,3])
f = np.array([4,5,6])
g = np.array([10,11,12])
np.vstack((e,f,g))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

hstack():
Merge arrays into single dimension

In [105]:
np.hstack((e,f))

array([1, 2, 3, 4, 5, 6])

column_stack():
merge the same column elements as on array

In [107]:
np.column_stack((e,f))

array([[1, 4],
       [2, 5],
       [3, 6]])

Intersection and Difference

In [122]:
q = np.array([19,67,38])
p = np.array([45,67,31])
np.intersect1d(q,p) # Return the common element

array([67])

In [123]:
np.setdiff1d(q,p) # Returns the different elements in 1 compared to 2

array([19, 38])

In [124]:
np.setdiff1d(p,q) # same as above

array([31, 45])

####Numpy array Mathemaics

In [129]:
np.sum([q,p],axis =1) # add array elements within

array([124, 143])

In [130]:
np.sum([q,p], axis =0) # add two arrays

array([ 64, 134,  69])

In [132]:
np.sum([q,p]) # Add all the elements

267

In [133]:
q = q +1 # adding the scalar to the numpy array
# Basic Addition
q

array([20, 68, 39])

In [135]:
q = q-4 # Basic subtraction
q

array([12, 60, 31])

In [137]:
q = q*5 # Basic Multipliacation
q

array([ 300, 1500,  775])

In [138]:
q = q/7 # Basc division
q

array([ 42.85714286, 214.28571429, 110.71428571])

* Basic Math Functions

In [141]:
t = np.array([21,32,43,54,60,57,67,89])
np.mean(t) # Mean

52.875

In [144]:
np.median(t) # Median

55.5

In [145]:
np.std(t) # Standard Deviation

19.757514393263136