<a href="https://colab.research.google.com/github/DasariRishikesh/Python_with_MachineLearning/blob/main/Python_with_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pyhton with Machine Learning

Pyhton consists of different types of libraries so that we need not to write the hard code every time. 
Here are some of the examples of the machine learnimg libraries and its uses.


1.   Numpy - Used for the numerical computation
2.   Pandas - Used for the data manipulatuion
3.   Matplotlib, Seaborn, plotly - Used for the data visualization



##Numpy

Numpy stands for Numerical python. It provides a multi dimensional arrays and number of functins or methods for the numerical compuation and scientific computation. 

#### Introduction to numpy

In [ ]:
import numpy as np
a = np.array([1,2,3,4])

*  Intialize array

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a2 = np.array([[1,2,3,4,5],[10,20,30,40]])

<ipython-input-18-ac16d04e47d0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1,2,3,4,5],[10,20,30,40]])


In [ ]:
a2

array([list([1, 2, 3, 4, 5]), list([10, 20, 30, 40])], dtype=object)

In [ ]:
type(a2) # type of the array

numpy.ndarray

*  Making Zeroes of all elements

In [ ]:
a1 = np.zeros((1,5))

In [ ]:
a1

array([[0., 0., 0., 0., 0.]])

In [ ]:
a2 = np.zeros((5,5))
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

*  Making The All elements same



full((size of the array along with the dimension), Value)

In [ ]:
k = np.full((3,3,3),1)

In [ ]:
k

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

*  Declare range of the arrray

(initial value, Final Value, Increment)

In [ ]:
l = np.arange(90,99,8)

In [ ]:
l

array([90, 98])

*  Passing random values

random.randint(start value,endvalue, Number of elements)

In [ ]:
 import numpy as np

In [ ]:
r = np.random.randint(3,7,4)
r

array([3, 6, 3, 6])

*  Random float points using rand

random.rand(number of rows or dimentions, number of rows in single dimension,Number of cloumns)

In [ ]:
ir = np.random.rand(2,5,4)
ir

array([[[0.85273206, 0.28958883, 0.87866551, 0.94574652],
        [0.12181155, 0.59262505, 0.20712191, 0.5142399 ],
        [0.06381569, 0.72896195, 0.1888137 , 0.72344889],
        [0.24185891, 0.3577034 , 0.37453504, 0.23581322],
        [0.66992718, 0.38863676, 0.25526386, 0.773159  ]],

       [[0.31008368, 0.20027366, 0.43278066, 0.74444885],
        [0.89748475, 0.66243957, 0.75853795, 0.97836724],
        [0.5296578 , 0.49393908, 0.48572778, 0.83055239],
        [0.27158704, 0.6976168 , 0.73196061, 0.10320711],
        [0.27813358, 0.56517061, 0.04490238, 0.32414503]]])

*  Shape and Reshape

In [ ]:
w = np.array([[[0.46632969, 0.3848112 , 0.83590619, 0.44005272], [0.9816671 , 0.10282616, 0.11472637, 0.28133451]], [[0.50586517, 0.2071658 , 0.99934125, 0.06517334], [0.93871074, 0.00633421, 0.5426788 , 0.85028254]]])
w.shape

(2, 2, 4)

In [ ]:
w.shape = (2,4,2)

In [ ]:
w

array([[[0.46632969, 0.3848112 ],
        [0.83590619, 0.44005272],
        [0.9816671 , 0.10282616],
        [0.11472637, 0.28133451]],

       [[0.50586517, 0.2071658 ],
        [0.99934125, 0.06517334],
        [0.93871074, 0.00633421],
        [0.5426788 , 0.85028254]]])

In [ ]:
z = np.array([[1,2,3,4],[5,6,7,8]])
z.shape = (4,2)
z


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Working with stack menthods in numpy, We have
*  vstack()
*  hstack()
*  column_stack()

V stack():
Merge n arrays in 2 dimension

In [ ]:
import numpy as np
e = np.array([1,2,3])
f = np.array([4,5,6])
g = np.array([10,11,12])
np.vstack((e,f,g))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

hstack():
Merge arrays into single dimension

In [ ]:
np.hstack((e,f))

array([1, 2, 3, 4, 5, 6])

column_stack():
merge the same column elements as on array

In [ ]:
np.column_stack((e,f))

array([[1, 4],
       [2, 5],
       [3, 6]])

Intersection and Difference

In [ ]:
q = np.array([19,67,38])
p = np.array([45,67,31])
np.intersect1d(q,p) # Return the common element

array([67])

In [ ]:
np.setdiff1d(q,p) # Returns the different elements in 1 compared to 2

array([19, 38])

In [ ]:
np.setdiff1d(p,q) # same as above

array([31, 45])

####Numpy array Mathemaics

In [ ]:
np.sum([q,p],axis =1) # add array elements within

array([124, 143])

In [ ]:
np.sum([q,p], axis =0) # add two arrays

array([ 64, 134,  69])

In [ ]:
np.sum([q,p]) # Add all the elements

267

In [ ]:
q = q +1 # adding the scalar to the numpy array
# Basic Addition
q

array([20, 68, 39])

In [ ]:
q = q-4 # Basic subtraction
q

array([12, 60, 31])

In [ ]:
q = q*5 # Basic Multipliacation
q

array([ 300, 1500,  775])

In [ ]:
q = q/7 # Basc division
q

array([ 42.85714286, 214.28571429, 110.71428571])

* Basic Math Functions

In [ ]:
import numpy as np
t = np.array([21,32,43,54,60,57,67,89])
np.mean(t) # Mean

52.875

In [ ]:
np.median(t) # Median

55.5

In [ ]:
np.std(t) # Standard Deviation

19.757514393263136

In [ ]:
np.max(t)  # maximumm value in the numpy array

89

In [ ]:
np.min(t)   # maximumm value in the numpy array

21

* Saving and Loading the Numpy Array

Using the Numpy.save we can store the array and .load to load the data

1. np.save('Name to save the array',array that want to be saved)

2. np.load('Name of the saved array')

In [ ]:
import numpy as np
L1 = np.array([77,44,33,22,88])
np.save('ThisArray',L1)                 # Saving the numpy array

In [ ]:
L2 = np.load('ThisArray.npy')          # Loading the numpy array
L2                                     # Should give the .npy(Essential) i.e., standard of numpy

array([77, 44, 33, 22, 88])

## Pandas

####Introduction to pandas

Pandas stands for the panel data. It's a core library for the data manupulation and the data analysis. It contains the single and multiple dimension DS and we perform the manipulation or analysis on this DS. 
* Single dimension  - Series object
* Multi dimension - Data Frame


######Series Object - Sigle Dimensional

In [ ]:
import pandas as pd
d = [9,10,66,42,9]
e = pd.Series(d)      

In [ ]:
e

0     9
1    10
2    66
3    42
4     9
dtype: int64

In [ ]:
e = pd.Series(d,index=['sportify','Gaana','Wink Music','Jio Saavan','Youtube Music'])    # change index

In [ ]:
e

sportify          9
Gaana            10
Wink Music       66
Jio Saavan       42
Youtube Music     9
dtype: int64

In [ ]:
type(e)

pandas.core.series.Series

In [ ]:
e2 = pd.Series({'a':1,'b':2,'c':3,'d':4})  # Print the series object of the disctionsy

In [ ]:
e2 # here we obeser the the key valeus are taken as the index values.

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# now change  the index values of the series object of the dictionary
e2 = pd.Series({'a':100,'b':2, 'c':300,'d':4,'e':500}, index = ['e','a','d','f','c'])
# Here we get the key values associated  values

In [ ]:
e2 # here you need to write the index values as the key values only if not  you get the values as the NAN 

e    500.0
a    100.0
d      4.0
f      NaN
c    300.0
dtype: float64

In [ ]:
# Extract Individual Elements
# Here we can them same as in python

s  = pd.Series([1,23,4,5,6,67])
s[4]

6

In [ ]:
s[2:]

2     4
3     5
4     6
5    67
dtype: int64

In [ ]:
s[:3]

0     1
1    23
2     4
dtype: int64

In [ ]:
s[:]

0     1
1    23
2     4
3     5
4     6
5    67
dtype: int64

In [ ]:
s[-2:]

4     6
5    67
dtype: int64

In [ ]:
# Scalar values addition to the series object
s+3

0     4
1    26
2     7
3     8
4     9
5    70
dtype: int64

In [ ]:
# Addding the series objects 
kyc = pd.Series([21,32,43,54,65,76])
kfc  = pd.Series([12,34,45,56,67,88])

In [ ]:
kyc + kfc

0     33
1     66
2     88
3    110
4    132
5    164
dtype: int64

######DataFrame in Padas - Multi dimensional labeled DS

In [ ]:
 # We create a DF with the dictionaries. 
 #As we create them using the dictionaries 
 #we get the keys as the column names and values as the rows

import pandas as pd
df = pd.DataFrame({'Class ID':[25,26,35,62,68,71,101],'Name':['Soma', 'Mani','Rishi','Balu','Sravan','Hassu','Ajay'],'CPI':[6.59,7.53,7.61,6.98,6.93,7.31,7.45]})

In [ ]:
df

Class ID    Name   CPI
0        25    Soma  6.59
1        26    Mani  7.53
2        35   Rishi  7.61
3        62    Balu  6.98
4        68  Sravan  6.93
5        71   Hassu  7.31
6       101    Ajay  7.45

Some of the inbuilt functions

* Head() - Look at the first 5 rows
* Tail() -  Look at the last few rows
* Shape() - look the rows and the columns
* Describe() - Get the description of the dataframe

In [ ]:
from sklearn import datasets
import pandas as pd
data = datasets.load_iris()

In [ ]:
# Here we are loading the iris dataset the web and trying to get the data from it
iris = pd.read_csv("https://datahub.io/machine-learning/iris/r/iris.csv", header = None)

In [ ]:
iris.head()

0           1            2           3            4
0  sepallength  sepalwidth  petallength  petalwidth        class
1          5.1         3.5          1.4         0.2  Iris-setosa
2          4.9         3.0          1.4         0.2  Iris-setosa
3          4.7         3.2          1.3         0.2  Iris-setosa
4          4.6         3.1          1.5         0.2  Iris-setosa

In [ ]:
iris.tail()

0    1    2    3               4
146  6.7  3.0  5.2  2.3  Iris-virginica
147  6.3  2.5  5.0  1.9  Iris-virginica
148  6.5  3.0  5.2  2.0  Iris-virginica
149  6.2  3.4  5.4  2.3  Iris-virginica
150  5.9  3.0  5.1  1.8  Iris-virginica

In [ ]:
iris.shape

(151, 5)

In [ ]:
iris.describe()

0    1    2    3            4
count   151  151  151  151          151
unique   36   24   44   23            4
top     5.0  3.0  1.5  0.2  Iris-setosa
freq     10   26   14   28           50

Extract the individual rows and columns form the Data frame

* .iloc() Method

In [ ]:
iris.iloc[3:, :2]

0    1
3    4.7  3.2
4    4.6  3.1
5    5.0  3.6
6    5.4  3.9
7    4.6  3.4
..   ...  ...
146  6.7  3.0
147  6.3  2.5
148  6.5  3.0
149  6.2  3.4
150  5.9  3.0

[148 rows x 2 columns]

In [ ]:
iris.iloc[5,0] # if you see this in the upper extracted table we get that

'5.0'

* .loc() method - only  the rows are extracted and column need to be given explicitly

In [ ]:
iris.loc[2:9,(3,0)]

3    0
2  0.2  4.9
3  0.2  4.7
4  0.2  4.6
5  0.2  5.0
6  0.4  5.4
7  0.3  4.6
8  0.2  5.0
9  0.2  4.4

* Drop the column with the drop() method

In [ ]:
iris.drop(3,axis = 1)

0           1            2               4
0    sepallength  sepalwidth  petallength           class
1            5.1         3.5          1.4     Iris-setosa
2            4.9         3.0          1.4     Iris-setosa
3            4.7         3.2          1.3     Iris-setosa
4            4.6         3.1          1.5     Iris-setosa
..           ...         ...          ...             ...
146          6.7         3.0          5.2  Iris-virginica
147          6.3         2.5          5.0  Iris-virginica
148          6.5         3.0          5.2  Iris-virginica
149          6.2         3.4          5.4  Iris-virginica
150          5.9         3.0          5.1  Iris-virginica

[151 rows x 4 columns]

In [ ]:
iris.drop(149,axis =0)

0           1            2           3               4
0    sepallength  sepalwidth  petallength  petalwidth           class
1            5.1         3.5          1.4         0.2     Iris-setosa
2            4.9         3.0          1.4         0.2     Iris-setosa
3            4.7         3.2          1.3         0.2     Iris-setosa
4            4.6         3.1          1.5         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.3          5.7         2.5  Iris-virginica
146          6.7         3.0          5.2         2.3  Iris-virginica
147          6.3         2.5          5.0         1.9  Iris-virginica
148          6.5         3.0          5.2         2.0  Iris-virginica
150          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris.drop([1,2,3,149],axis = 0)

0           1            2           3               4
0    sepallength  sepalwidth  petallength  petalwidth           class
4            4.6         3.1          1.5         0.2     Iris-setosa
5            5.0         3.6          1.4         0.2     Iris-setosa
6            5.4         3.9          1.7         0.4     Iris-setosa
7            4.6         3.4          1.4         0.3     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.3          5.7         2.5  Iris-virginica
146          6.7         3.0          5.2         2.3  Iris-virginica
147          6.3         2.5          5.0         1.9  Iris-virginica
148          6.5         3.0          5.2         2.0  Iris-virginica
150          5.9         3.0          5.1         1.8  Iris-virginica

[147 rows x 5 columns]

 Pandas Functions
* mean()
* median()
* max()
* min()

In [ ]:
iris.min()

0            4.3
1            2.0
2            1.0
3            0.1
4    Iris-setosa
dtype: object

In [ ]:
iris.max()

0    sepallength
1     sepalwidth
2    petallength
3     petalwidth
4          class
dtype: object

In [ ]:
q = iris.drop(0, axis =0)
q = pd.DataFrame(q)
q

0    1    2    3               4
1    5.1  3.5  1.4  0.2     Iris-setosa
2    4.9  3.0  1.4  0.2     Iris-setosa
3    4.7  3.2  1.3  0.2     Iris-setosa
4    4.6  3.1  1.5  0.2     Iris-setosa
5    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
146  6.7  3.0  5.2  2.3  Iris-virginica
147  6.3  2.5  5.0  1.9  Iris-virginica
148  6.5  3.0  5.2  2.0  Iris-virginica
149  6.2  3.4  5.4  2.3  Iris-virginica
150  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
q = q.astype({0:'float',1:'float',2:'float',3:'float'})
q = pd.DataFrame(q)
q

0    1    2    3               4
1    5.1  3.5  1.4  0.2     Iris-setosa
2    4.9  3.0  1.4  0.2     Iris-setosa
3    4.7  3.2  1.3  0.2     Iris-setosa
4    4.6  3.1  1.5  0.2     Iris-setosa
5    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
146  6.7  3.0  5.2  2.3  Iris-virginica
147  6.3  2.5  5.0  1.9  Iris-virginica
148  6.5  3.0  5.2  2.0  Iris-virginica
149  6.2  3.4  5.4  2.3  Iris-virginica
150  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
q.mean()

<ipython-input-181-210cb2be4f7f>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  q.mean()


0    5.843333
1    3.054000
2    3.758667
3    1.198667
dtype: float64

In [ ]:
q.median()

<ipython-input-182-151862b3b14e>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  q.median()


0    5.80
1    3.00
2    4.35
3    1.30
dtype: float64

* Apply() - Method

In [ ]:
def square(s):
  return float(s)**2

In [ ]:
q[1].apply(square)

1      12.25
2       9.00
3      10.24
4       9.61
5      12.96
       ...  
146     9.00
147     6.25
148     9.00
149    11.56
150     9.00
Name: 1, Length: 150, dtype: float64

In [ ]:
q[4].value_counts() # used to get the values of the a number or the variable occured in that column

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: 4, dtype: int64

In [ ]:
q.sort_values(by = 1) # Get the order of the column according to the incresing order.

0    1    2    3                4
61   5.0  2.0  3.5  1.0  Iris-versicolor
63   6.0  2.2  4.0  1.0  Iris-versicolor
120  6.0  2.2  5.0  1.5   Iris-virginica
69   6.2  2.2  4.5  1.5  Iris-versicolor
42   4.5  2.3  1.3  0.3      Iris-setosa
..   ...  ...  ...  ...              ...
17   5.4  3.9  1.3  0.4      Iris-setosa
15   5.8  4.0  1.2  0.2      Iris-setosa
33   5.2  4.1  1.5  0.1      Iris-setosa
34   5.5  4.2  1.4  0.2      Iris-setosa
16   5.7  4.4  1.5  0.4      Iris-setosa

[150 rows x 5 columns]

In [ ]:
iris.iloc[6:0,4:0]

Empty DataFrame
Columns: []
Index: []